apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5000         # External port for accessing the first container
      targetPort: 3000   # Internal port on the first container
  type: LoadBalancer      # Change to ClusterIP if you only need internal access
