name: CI/CD Pipeline # Name of the workflow

on:
  push:
    branches:
      - master # Trigger the workflow on push events to the 'master' branch
  pull_request:
    branches:
      - master # Trigger the workflow on pull requests targeting the 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest # The environment to run the job on

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Checks out the source code from the repository

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Sets up Node.js version 16 for the workflow

      - name: Install dependencies
        run: npm install # Installs npm dependencies required for the project

      - name: Run code linting
        run: npm run lint # Lints the code to check for syntax and style issues

      - name: Run tests
        run: npm run test # Runs tests

      - name: Build application
        run: npm run build # Builds the React application

      - name: Build Docker image
        run: docker build -t student-list-group-3:latest . # Builds a Docker image for the application

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }} # Docker Hub username from repository secrets
          password: ${{ secrets.DOCKER_HUB_PASSWORD }} # Docker Hub password from repository secrets

      - name: Push Docker image to Docker Hub
        run: |
          docker tag student-list-group-3:latest ${{ secrets.DOCKER_HUB_USERNAME }}/student-list-group-3:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/student-list-group-3:latest

      - name: Set up Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube /usr/local/bin/
          mkdir -p $HOME/.kube $HOME/.minikube
          sudo chown -R $USER $HOME/.kube $HOME/.minikube
          kubectl config view --merge --flatten > $HOME/.kube/config

      - name: Deployment # Correctly formatted step
        run: |
          minikube start
          minikube status
          kubectl apply -f k8s/configmap.yaml --validate=false
          kubectl apply -f k8s/deployment.yaml --validate=false
          kubectl apply -f k8s/service.yaml --validate=false
          kubectl get all
