name: CI/CD Pipeline # Name of the workflow

on:
  push:
    branches:
      - dev # Trigger the workflow on push events to the 'dev' branch
  pull_request:
    branches:
      - dev # Trigger the workflow on pull requests targeting the 'dev' branch

jobs:
  build:
    runs-on: ubuntu-latest # The environment to run the job on

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Checks out the source code from the repository

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Sets up Node.js version 16 for the workflow

      - name: Install dependencies
        run: npm install # Installs npm dependencies required for the project

      - name: Run code linting
        run: npm run lint # Lints the code to check for syntax and style issues

      - name: Run tests
        run: npm test -- --coverage # Runs tests and generates coverage reports

      - name: Build application
        run: npm run build # Builds the React application
